"""Schroders v2 mined dictionary — generalised full-universe build,
post-hygiene (see pipeline/clean_dictionary.py for the rules and
pipeline_output/dictionary_hygiene_audit.json for the audit trail)."""

DICTIONARY_VERSION = '2026-07-22-v3.1-generalised-clean'

SCHRODERS_V2_DIMENSIONS = [
    "b01",
    "b02",
    "b03",
    "b04",
    "b05",
    "b06",
    "b07",
    "b08",
    "b09",
    "b10",
    "b11",
    "b12"
]

SCHRODERS_V2_KEYWORDS = {
    'b01': {
        'positive': {
            'a bright future': 0.57,
            'a future': 0.577,
            'a long career': 0.641,
            'a long term': 0.736,
            'a long-term career': 0.695,
            'a long-term strategy': 1.0,
            'a long-term view': 1.0,
            'a long-term vision': 1.0,
            'better future': 0.559,
            'bright future': 0.552,
            'builds for the long run': 1.0,
            'career progression': 0.583,
            'future': 1.512,
            'future business': 0.581,
            'future focused': 1.0,
            'future plans': 0.577,
            'future prospects': 0.569,
            'future vision': 0.578,
            'good career progression': 0.561,
            'good future': 0.55,
            'good investment': 0.551,
            'invests for the future': 1.0,
            'limited career progression': 0.558,
            'long career': 0.663,
            'long decision': 0.585,
            'long duration': 0.571,
            'long projects': 0.589,
            'long term career': 0.714,
            'long term employee': 0.605,
            'long term employees': 0.617,
            'long term employment': 0.652,
            'long term goals': 0.714,
            'long term growth': 0.738,
            'long term projects': 0.737,
            'long term strategy': 1.802,
            'long term success': 0.733,
            'long term thinking': 1.0,
            'long term view': 1.0,
            'long term vision': 1.74,
            'long years': 0.611,
            'long-term': 0.798,
            'long-term employees': 0.607,
            'long-term growth': 0.738,
            'long-term strategy': 0.999,
            'long-term success': 0.737,
            'long-term thinking': 0.903,
            'long-term view': 0.963,
            'long-term vision': 1.0,
            'longevity': 0.574,
            'multiple years': 0.558,
            'patient capital': 1.0,
            'progression opportunities': 0.582,
            'stability': 0.778,
            'stable company': 0.602,
            'sustainable growth': 1.504,
            'the foreseeable future': 0.551,
            'the future': 0.581,
            'the long haul': 0.552,
            'the long run': 0.55,
            'the long term': 0.779,
            'the long-term': 0.795,
            'the long-term strategy': 0.963,
            'the long-term vision': 0.784,
            'thinks long term': 1.0,
            'your career progression': 0.577,
        },
        'negative': {
            'a short period': 0.516,
            'a short time': 0.525,
            'always short': 0.531,
            'budgets': 0.463,
            'chasing quarterly numbers': 1.0,
            'easy task': 0.468,
            'extremely short': 1.315,
            'fast track': 0.514,
            'financial targets': 0.551,
            'high targets': 0.484,
            'hit the numbers': 1.0,
            'incredibly short': 0.828,
            'limited scope': 0.472,
            'little focus': 0.459,
            'little progression': 0.496,
            'monthly goals': 0.54,
            'monthly targets': 1.614,
            'my short time': 0.495,
            'numbers': 0.536,
            'quarterly goals': 0.65,
            'quarterly numbers': 0.493,
            'quarterly results': 0.541,
            'quarterly targets': 1.0,
            'quick cash': 0.482,
            'quick learner': 0.462,
            'quick learning': 0.503,
            'quick money': 0.554,
            'quick pace': 0.462,
            'quick promotion': 0.465,
            'quick response': 0.469,
            'quick wins': 1.0,
            'relatively short': 0.47,
            'results': 0.535,
            'revenue': 1.056,
            'sales targets': 0.513,
            'short': 0.561,
            'short amount': 0.489,
            'short break': 0.484,
            'short contract': 0.498,
            'short contracts': 0.52,
            'short cuts': 0.544,
            'short duration': 0.552,
            'short period': 0.532,
            'short periods': 0.58,
            'short sighted': 1.0,
            'short sighted decisions': 1.0,
            'short sighted goals': 0.597,
            'short sighted leadership': 0.597,
            'short sighted management': 1.0,
            'short span': 0.503,
            'short term': 1.166,
            'short term focus': 1.0,
            'short term goals': 0.715,
            'short term results': 1.0,
            'short term thinking': 1.0,
            'short time': 0.577,
            'short-sighted decisions': 0.615,
            'short-sighted leadership': 0.568,
            'short-sighted management': 0.981,
            'short-term': 0.753,
            'short-term focus': 0.99,
            'short-term results': 0.845,
            'slow months': 0.474,
            'so short': 1.487,
            'targets': 0.489,
            'terms': 0.611,
            'the monthly targets': 0.828,
            'the numbers': 1.0,
            'the short term': 0.698,
            'the short time': 0.558,
            'the terms': 0.469,
            'too short': 1.468,
            'very short': 1.367,
            'your monthly targets': 0.903,
            'your sales goals': 0.463,
        },
    },
    'b02': {
        'positive': {
            'a growing company': 0.744,
            'a growth mindset': 1.706,
            'an investment': 0.681,
            'better growth': 0.688,
            'business growth': 0.711,
            'company growth': 0.686,
            'continued growth': 0.728,
            'excellent growth opportunities': 0.711,
            'exciting growth': 0.709,
            'expanding into new markets': 1.0,
            'fast growing company': 0.763,
            'fast growth': 0.727,
            'faster growth': 0.705,
            'few growth': 0.673,
            'further growth': 0.778,
            'future growth': 0.717,
            'good growth': 0.672,
            'good growth opportunities': 0.731,
            'good growth opportunity': 0.727,
            'great growth opportunities': 0.735,
            'great growth opportunity': 0.741,
            'growing business': 0.821,
            'growing company': 0.768,
            'growing fast': 1.0,
            'growing opportunities': 0.746,
            'growth mindset': 1.675,
            'growth opportunities': 0.769,
            'growth opportunity': 0.766,
            'growth path': 0.669,
            'growth prospects': 0.713,
            'high growth': 0.696,
            'hiring aggressively': 1.0,
            'huge growth': 0.706,
            'huge investment': 0.732,
            'incredible growth': 0.67,
            'internal growth': 0.671,
            'investing': 0.671,
            'investing in growth': 1.0,
            'investment': 0.696,
            'investments': 0.672,
            'invests': 1.322,
            'invests in new products': 1.0,
            'invests in technology': 1.0,
            'less growth opportunities': 0.727,
            'less growth opportunity': 0.724,
            'limited growth': 0.722,
            'limited growth opportunities': 0.735,
            'limited growth opportunity': 0.722,
            'many growth': 0.707,
            'many growth opportunities': 0.755,
            'massive growth': 0.714,
            'more growth': 0.731,
            'more growth opportunities': 0.781,
            'more investment': 0.735,
            'much growth': 0.72,
            'new markets': 1.548,
            'own growth': 0.697,
            'quick growth': 0.7,
            'rapid expansion': 1.582,
            'rapid growth': 0.695,
            'real growth': 0.713,
            'scaling the business': 1.0,
            'significant growth': 0.706,
            'slower growth': 0.68,
            'some growing pains': 0.732,
            'strong growth': 1.626,
            'strong investment': 0.686,
            'technical growth': 0.686,
            'the growth': 0.749,
            'the growth mindset': 1.0,
            'the growth opportunities': 0.77,
            'the investment': 0.705,
            'the rapid expansion': 0.88,
            'the rapid growth': 0.693,
            'tremendous growth': 0.698,
            'unlimited growth': 0.705,
            'well funded': 1.0,
        },
        'negative': {
            'a cheap company': 1.0,
            'aggressive cost': 1.0,
            'as cheap': 1.0,
            'budget': 0.717,
            'budget cuts': 1.751,
            'budgeting': 0.729,
            'canteen': 1.0,
            'cheap': 1.0,
            'cheap benefits': 1.0,
            'cheap cable': 1.0,
            'cheap canteen': 1.0,
            'cheap company': 1.571,
            'cheap cost': 1.0,
            'cheap flights': 1.0,
            'cheap food': 1.57,
            'cheap health': 1.0,
            'cheap health insurance': 1.0,
            'cheap insurance': 1.0,
            'cheap labor': 1.648,
            'cheap labour': 1.596,
            'cheap lunch': 1.0,
            'cheap management': 1.0,
            'cheap meals': 1.0,
            'cheap pay': 1.0,
            'cheap people': 1.0,
            'cheap phone': 1.0,
            'cheap place': 1.0,
            'cheap politics': 1.523,
            'cheap price': 1.0,
            'cheap prices': 1.0,
            'cheap products': 1.0,
            'cheap salary': 1.0,
            'cheap tickets': 1.0,
            'constant budget': 1.0,
            'constant budget cuts': 1.0,
            'constant cost': 1.539,
            'constant cost cutting': 1.0,
            'continuous cost': 1.0,
            'contractors': 1.0,
            'cost': 1.609,
            'cost cutting': 1.649,
            'cost cutting initiatives': 1.0,
            'cost cutting measures': 1.0,
            'cost cutting mode': 1.0,
            'cost-cutting': 1.725,
            'cost-cutting measures': 1.0,
            'costs': 1.651,
            'cutting': 1.0,
            'cutting corners on cost': 1.0,
            'do more with less': 1.0,
            'expenses': 1.567,
            'extreme cost': 1.0,
            'extremely cheap': 1.0,
            'frugal': 1.0,
            'headcount freeze': 1.0,
            'just cheap': 1.0,
            'layoffs': 1.0,
            'less mentality': 1.0,
            'less people': 1.476,
            'less resources': 1.509,
            'major cost': 1.0,
            'more budget': 0.722,
            'much cost': 1.584,
            'penny': 1.0,
            'penny pinching': 1.0,
            'pretty cheap': 1.0,
            'really cheap': 1.0,
            'recent cost': 1.0,
            'redundancies': 1.0,
            'relatively cheap': 1.0,
            'so cheap': 1.574,
            'super cheap': 1.0,
            'the cost cutting': 1.0,
            'tight budgets': 1.748,
            'too cheap': 1.579,
            'understaffed to save money': 1.0,
            'very cheap': 1.516,
            'very cheap company': 1.0,
            'very frugal': 1.0,
        },
    },
    'b03': {
        'positive': {
            'a flat structure': 1.0,
            'a friendly environment': 0.529,
            'a voice': 0.799,
            'access': 0.319,
            'accessible leadership': 1.0,
            'an open-door policy': 1.0,
            'approachable colleagues': 0.516,
            'autonomy': 0.637,
            'autonomy to make decisions': 1.0,
            'capable colleagues': 0.535,
            'capable employees': 0.517,
            'collaborative decision making': 1.0,
            'collaborative people': 0.531,
            'collaborative workplace': 0.529,
            'cooperation': 0.537,
            'cooperative staff': 0.538,
            'door policy': 1.0,
            'easily approachable': 0.337,
            'easy access': 0.35,
            'egalitarian culture': 1.0,
            'employee empowerment': 0.511,
            'employee engagement': 0.292,
            'employee friendly': 0.511,
            'employee friendly organization': 0.534,
            'empowered employees': 1.0,
            'empowerment': 0.523,
            'everyone has a voice': 1.0,
            'fairly flat': 1.0,
            'fairly flat structure': 0.88,
            'flat hierarchy': 1.511,
            'flat organisation': 0.599,
            'flat structure': 1.0,
            'friendly culture': 0.319,
            'friendly organisation': 0.577,
            'friendly organization': 0.566,
            'friendly work': 0.513,
            'friendly workplace': 0.518,
            'full autonomy': 0.626,
            'good autonomy': 0.586,
            'great autonomy': 0.572,
            'high autonomy': 0.63,
            'inclusive culture': 0.289,
            'individual development': 0.509,
            'individuality': 0.528,
            'leadership listens': 1.0,
            'limited autonomy': 0.636,
            'limited roles': 0.527,
            'little autonomy': 0.566,
            'more autonomy': 0.625,
            'more flat': 0.672,
            'much autonomy': 0.582,
            'nice colleagues': 0.366,
            'open culture': 0.327,
            'open door': 1.0,
            'open door policy': 1.0,
            'open office': 0.337,
            'open roles': 0.547,
            'open-door policy': 1.0,
            'pretty flat': 0.568,
            'rather flat': 0.799,
            'relatively flat': 1.0,
            'relatively flat structure': 1.0,
            'respectful workplace': 0.527,
            'the autonomy': 0.945,
            'the flat structure': 1.0,
            'the open-door policy': 1.0,
            'transparent leadership': 0.616,
            'truly open': 0.828,
            'very accessible': 0.624,
            'very flat': 1.0,
            'very flat structure': 1.0,
        },
        'negative': {
            'bureaucratic hierarchy': 1.0,
            'chain': 1.0,
            'chain of command': 1.0,
            'clear chain': 1.0,
            'command': 1.0,
            'constant micromanagement': 1.617,
            'decisions made at the top': 1.0,
            'down management': 1.597,
            'excessive micromanagement': 1.0,
            'extreme micromanagement': 1.627,
            'heavy micromanagement': 1.0,
            'heavy workload': 1.0,
            'hierarchical company': 1.623,
            'hierarchical management': 1.768,
            'hierarchical organization': 1.719,
            'hierarchical structure': 1.635,
            'hierarchy': 0.729,
            'high level management': 0.739,
            'high stress': 1.0,
            'higher level management': 0.723,
            'intense micromanagement': 1.0,
            'know your place': 1.0,
            'layers': 1.0,
            'layers of management': 1.0,
            'less micromanagement': 1.621,
            'long chain': 1.0,
            'many layers': 1.0,
            'micromanagement': 1.114,
            'micromanagement culture': 1.0,
            'micromanagement environment': 1.0,
            'micromanagement issues': 1.0,
            'micromanagement style': 1.0,
            'micromanagement, lack': 1.0,
            'middle level management': 0.719,
            'minimal micromanagement': 1.0,
            'more layers': 1.0,
            'more micromanagement': 1.0,
            'much micromanagement': 1.634,
            'multiple layers': 1.0,
            'rigid hierarchy': 1.573,
            'senior leadership decides everything': 1.0,
            'several layers': 1.0,
            'severe micromanagement': 1.0,
            'slow decision': 1.0,
            'so many layers': 1.0,
            'some micromanagement': 1.0,
            'sometimes micromanagement': 1.0,
            'the chain': 1.0,
            'the extreme': 1.0,
            'the hierarchy': 0.759,
            'the layers': 1.0,
            'the level': 1.0,
            'the management level': 0.724,
            'the management structure': 0.733,
            'the micromanagement': 1.662,
            'the top management': 0.752,
            'too many layers': 1.0,
            'top down management': 1.724,
            'top level management': 0.748,
            'top management': 0.732,
            'top-down management': 1.0,
            'top-down management style': 1.0,
            'toxic micromanagement': 1.0,
            'unnecessary layers': 1.0,
            'unnecessary micromanagement': 1.0,
            'upper level management': 0.733,
            'very hierarchical': 1.691,
            'very hierarchical company': 1.0,
            'very hierarchical organization': 1.0,
            'very hierarchical structure': 1.0,
            'very micromanagement': 1.0,
            'very top': 1.0,
        },
    },
    'b04': {
        'positive': {
            'a decision': 0.565,
            'a flexible approach': 0.924,
            'a willingness': 0.527,
            'adapt quickly': 1.0,
            'adaptability': 0.575,
            'adaptation': 0.539,
            'adapts to change': 1.0,
            'agile ways': 1.0,
            'agile ways of working': 1.0,
            'always nimble': 0.828,
            'approach': 0.583,
            'approaches': 0.552,
            'as nimble': 0.944,
            'better coordination': 0.527,
            'better decisions': 0.541,
            'big decisions': 0.526,
            'business decisions': 0.529,
            'certain decisions': 0.605,
            'common sense': 0.526,
            'common sense over process': 1.0,
            'consideration': 0.582,
            'coordination': 0.581,
            'decision': 0.544,
            'decision makers': 0.57,
            'decision making': 0.585,
            'decision-making': 0.565,
            'decisions': 0.622,
            'design': 0.519,
            'determination': 0.546,
            'difficult decisions': 0.565,
            'fast decision': 0.563,
            'faster decision': 0.556,
            'flexible approach': 1.566,
            'freedom': 0.838,
            'freedom to decide': 1.0,
            'important decisions': 0.541,
            'informed decisions': 0.536,
            'judgement': 0.536,
            'key decisions': 0.561,
            'less nimble': 1.0,
            'manipulation': 0.546,
            'many decisions': 0.551,
            'more approachable': 0.552,
            'more decisions': 0.539,
            'more nimble': 1.0,
            'more pragmatic': 0.934,
            'nimble': 1.0,
            'nimble companies': 0.963,
            'nimble company': 1.0,
            'nimble competitors': 0.999,
            'nimble organization': 1.0,
            'own decisions': 0.554,
            'pragmatic': 1.0,
            'pragmatic approach': 0.963,
            'pragmatic management': 0.799,
            'quick decision': 0.527,
            'quick decisions': 0.629,
            'right decisions': 0.542,
            'slow decisions': 0.555,
            'slower decision': 0.522,
            'some decisions': 0.569,
            'the decision': 0.545,
            'the decision making': 0.587,
            'the decisions': 0.595,
            'the right decisions': 0.585,
            'this approach': 0.544,
            'trusted to make decisions': 1.0,
            'use your judgement': 1.0,
            'very nimble': 1.0,
            'very pragmatic': 1.0,
            'willingness': 0.528,
            'your approach': 0.518,
        },
        'negative': {
            'a process': 0.608,
            'administrative red tape': 1.0,
            'approval': 0.58,
            'approvals': 1.541,
            'barriers': 0.963,
            'better processes': 0.58,
            'bureaucratic red tape': 1.0,
            'by the book': 1.0,
            'checklists for everything': 1.0,
            'compliance': 0.611,
            'compliance driven': 1.0,
            'complicated processes': 0.587,
            'corporate red tape': 1.0,
            'cumbersome processes': 0.57,
            'endless red tape': 0.924,
            'established processes': 0.612,
            'every process': 0.648,
            'everything needs approval': 1.0,
            'excessive red tape': 1.0,
            'follow the process': 1.0,
            'good processes': 0.63,
            'great processes': 0.566,
            'heavy process': 0.572,
            'highly regulated': 1.458,
            'inflexible rules': 1.0,
            'internal red tape': 1.0,
            'large amount': 0.924,
            'less red tape': 1.0,
            'manual processes': 0.574,
            'many process': 0.579,
            'more process': 0.595,
            'more processes': 0.606,
            'more red tape': 1.0,
            'much process': 0.582,
            'much processes': 0.616,
            'much red tape': 1.0,
            'new processes': 0.571,
            'paperwork': 1.459,
            'policies': 1.469,
            'process': 1.6,
            'process heavy': 1.0,
            'processes': 0.617,
            'processing': 0.591,
            'progress': 1.495,
            'proper process': 0.642,
            'red tape': 1.465,
            'red-tape': 1.47,
            'regulated industry': 0.924,
            'rigid procedures': 1.0,
            'slow processes': 1.0,
            'some process': 0.612,
            'some processes': 0.591,
            'some red tape': 1.465,
            'streamlined processes': 0.581,
            'strict compliance': 0.601,
            'strict processes': 1.0,
            'strict rules': 0.58,
            'strong process': 0.6,
            'strong processes': 0.569,
            'structured processes': 0.585,
            'tape': 0.924,
            'the procedures': 0.596,
            'the process': 1.64,
            'the processes': 0.648,
            'the red tape': 1.0,
            'the red-tape': 1.0,
            'the workflow': 0.583,
            'their process': 0.588,
            'this process': 0.604,
            'too much bureaucracy': 1.46,
            'too much process': 0.569,
            'too much red-tape': 1.0,
            'typical red tape': 0.963,
            'unnecessary red tape': 1.0,
            'very process': 1.57,
            'very strict': 0.981,
            'your processes': 0.619,
        },
    },
    'b05': {
        'positive': {
            'a collaborative environment': 1.653,
            'a team': 1.708,
            'a team environment': 0.775,
            'amazing team': 1.0,
            'cohesive team': 0.743,
            'collaboration': 0.759,
            'collaborative culture': 1.604,
            'collaborative environment': 1.08,
            'collaborative team': 1.857,
            'collaborative teams': 0.84,
            'collaborative work': 1.703,
            'collective success': 1.0,
            'cooperative colleagues': 0.73,
            'cooperative team': 0.816,
            'cross functional collaboration': 1.0,
            'cross-functional collaboration': 1.627,
            'everyone helps each other': 1.0,
            'excellent team': 1.0,
            'excellent team spirit': 1.0,
            'excellent work': 1.0,
            'functional collaboration': 1.659,
            'good collaborative environment': 1.0,
            'good team spirit': 1.58,
            'good work culture': 1.0,
            'great collaborative environment': 1.0,
            'great management': 1.0,
            'great team spirit': 1.0,
            'great teamwork': 1.692,
            'great teamwork environment': 1.0,
            'great work environment': 1.0,
            'great working': 1.0,
            'great working environment': 1.0,
            'helpful team': 0.753,
            'helpful teams': 0.754,
            'highly collaborative': 1.66,
            'highly collaborative environment': 1.0,
            'hybrid work': 1.0,
            'knowledge sharing': 1.0,
            'more collaborative': 1.687,
            'nice environment': 1.0,
            'nice team': 1.0,
            'open communication': 1.0,
            'strong collaboration': 0.731,
            'strong team': 1.641,
            'strong team spirit': 1.0,
            'strong teamwork': 0.743,
            'support teams': 0.74,
            'supportive colleagues': 1.639,
            'supportive team': 1.131,
            'team building': 0.785,
            'team collaboration': 0.849,
            'team dynamics': 0.746,
            'team environment': 0.748,
            'team first': 1.0,
            'team members': 0.77,
            'team oriented': 1.0,
            'team oriented environment': 1.0,
            'team spirit': 1.658,
            'team structure': 0.739,
            'team support': 0.769,
            'team work': 0.84,
            'teammates': 0.74,
            'teamwork': 0.811,
            'the collaborative environment': 1.0,
            'the team environment': 0.739,
            'the team spirit': 1.0,
            'the teamwork': 0.822,
            'very collaborative': 1.66,
            'very collaborative environment': 1.633,
            'very friendly': 1.0,
            'very supportive colleagues': 1.0,
            'very team': 1.623,
            'work as a team': 1.0,
        },
        'negative': {
            'a competitive environment': 0.606,
            'a competitor': 0.58,
            'a sink': 0.855,
            'competition': 0.714,
            'competitions': 0.594,
            'competitive base': 0.587,
            'competitive colleagues': 1.0,
            'competitive culture': 0.569,
            'competitive nature': 0.605,
            'competitive people': 0.666,
            'competitive place': 0.601,
            'competitive workplace': 0.591,
            'competitiveness': 0.617,
            'competitor': 0.601,
            'competitors': 0.635,
            'cutthroat competition': 1.0,
            'deep end': 1.0,
            'every man': 1.0,
            'every man for himself': 1.0,
            'extremely competitive': 0.565,
            'fierce competition': 0.625,
            'high competition': 0.627,
            'highly competitive': 0.569,
            'himself': 1.0,
            'individual targets': 1.0,
            'intense competition': 0.609,
            'internal competition': 1.105,
            'its sink': 0.799,
            'longer competitive': 0.564,
            'many competitors': 0.606,
            'more competition': 0.59,
            'more competitive': 0.563,
            'most competitive': 0.577,
            'most competitors': 0.572,
            'much competition': 0.58,
            'my peers': 0.577,
            'other competitors': 0.588,
            'our competitors': 0.583,
            'overly competitive': 0.583,
            'personal quotas': 1.0,
            'ranking': 0.75,
            'sharp elbows': 1.0,
            'sink': 1.0,
            'sink or swim': 1.0,
            'some competitors': 0.629,
            'some internal competition': 0.855,
            'stack': 0.88,
            'stack ranking': 1.0,
            'star culture': 1.0,
            'stiff competition': 0.598,
            'strong competition': 0.638,
            'strong internal competition': 0.981,
            'swim': 1.0,
            'swim approach': 0.799,
            'swim atmosphere': 0.963,
            'swim attitude': 0.99,
            'swim culture': 1.0,
            'swim environment': 1.0,
            'swim mentality': 1.0,
            'swim situation': 1.0,
            'swim type': 1.0,
            'the competition': 0.667,
            'the competitors': 0.636,
            'the deep end': 0.944,
            'the internal competition': 1.0,
            'the ranks': 0.564,
            'the sink': 0.944,
            'their competitors': 0.566,
            'their peers': 0.581,
            'too competitive': 0.563,
            'tough competition': 0.592,
            'toxic culture': 0.488,
            'very sink': 1.0,
            'your competition': 0.569,
            'your competitors': 0.604,
            'your peers': 0.6,
        },
    },
    'b06': {
        'positive': {
            'a customer': 1.482,
            'aggressive customers': 0.7,
            'business': 0.711,
            'centric approach': 1.0,
            'centric company': 1.541,
            'centric organisation': 0.903,
            'certain customers': 0.736,
            'close to the market': 1.0,
            'current customers': 0.701,
            'customer': 1.709,
            'customer base': 0.688,
            'customer care': 0.735,
            'customer centric': 1.726,
            'customer centric approach': 1.0,
            'customer centric company': 0.981,
            'customer centric culture': 0.828,
            'customer centric organization': 0.799,
            'customer experience': 0.69,
            'customer facing': 0.698,
            'customer first': 1.0,
            'customer first approach': 0.944,
            'customer first culture': 0.944,
            'customer first mentality': 0.963,
            'customer focus': 0.813,
            'customer focused': 1.0,
            'customer focused company': 0.963,
            'customer interaction': 0.703,
            'customer interactions': 0.705,
            'customer needs': 1.146,
            'customer obsessed': 1.0,
            'customer relations': 0.683,
            'customer satisfaction': 1.49,
            'customer service': 0.688,
            'customer services': 0.714,
            'customer success': 0.674,
            'customer-centric': 1.0,
            'customer-centric approach': 0.88,
            'different customers': 0.701,
            'difficult customers': 0.674,
            'each customer': 0.686,
            'employee centric': 0.693,
            'externally focused': 1.0,
            'friendly customers': 0.697,
            'good customer': 1.375,
            'good customers': 0.679,
            'great customer': 1.0,
            'in tune with the industry': 1.0,
            'interesting customers': 0.682,
            'internal customers': 0.74,
            'its customers': 0.762,
            'listens to customers': 1.0,
            'loyal customers': 0.701,
            'many customers': 0.699,
            'market': 0.972,
            'market driven': 1.0,
            'marketing': 0.683,
            'more customer': 1.65,
            'more customer centric': 1.0,
            'more customers': 0.737,
            'most customers': 0.723,
            'my customers': 0.68,
            'new customers': 0.703,
            'our customers': 1.08,
            'potential customers': 0.745,
            'responsive to clients': 1.0,
            'services': 1.02,
            'some customers': 0.736,
            'strong customer': 1.3,
            'the customer': 1.707,
            'the customer base': 0.703,
            'the customer experience': 0.705,
            'the customer service': 0.691,
            'the customers': 0.91,
            'their customers': 0.751,
            'very customer': 1.606,
            'very customer centric': 1.0,
            'very employee': 0.799,
            'your customers': 1.294,
        },
        'negative': {
            'a big focus': 0.539,
            'a focus': 0.555,
            'a strong focus': 0.569,
            'an ivory tower': 1.0,
            'bad internal politics': 0.981,
            'bad work': 0.944,
            'behind the times': 1.0,
            'bureaucracy': 0.746,
            'egos': 0.799,
            'focus': 0.556,
            'heavy internal politics': 1.0,
            'high internal politics': 0.88,
            'huge internal politics': 0.828,
            'insular culture': 1.0,
            'internal business': 0.601,
            'internal company': 0.55,
            'internal competition': 0.376,
            'internal culture': 0.625,
            'internal job': 0.543,
            'internal management': 0.54,
            'internal movement': 0.544,
            'internal opportunities': 0.584,
            'internal opportunity': 0.595,
            'internal organization': 0.565,
            'internal people': 0.573,
            'internal politics': 1.607,
            'internal talent': 0.543,
            'internal technology': 0.57,
            'internal work': 0.569,
            'internally focused': 1.0,
            'inward looking': 1.0,
            'ivory tower': 1.0,
            'less growth': 0.855,
            'many internal politics': 0.88,
            'more internal': 0.61,
            'more internal politics': 0.963,
            'much internal politics': 0.944,
            'navel gazing': 1.0,
            'nepotism': 0.667,
            'out of touch with the market': 1.0,
            'outside company': 0.55,
            'outside experience': 0.571,
            'outside world': 0.578,
            'real focus': 0.543,
            'recognition': 1.0,
            'resistant to outside ideas': 1.0,
            'some areas': 0.903,
            'some internal politics': 1.0,
            'some projects': 0.855,
            'sometimes internal': 1.0,
            'strong focus': 0.547,
            'syndrome': 0.799,
            'the direction': 0.545,
            'the focus': 0.57,
            'the forefront': 0.571,
            'the inside': 0.625,
            'the internal politics': 1.614,
            'the ivory tower': 1.0,
            'the main focus': 0.538,
            'the outside': 0.588,
            'the outside world': 0.615,
            'the projects': 0.799,
            'the times': 1.0,
            'the transparency': 0.537,
            'their ivory tower': 1.0,
            'very insular': 0.799,
            'visibility': 1.347,
            'your ivory tower': 1.0,
        },
    },
    'b07': {
        'positive': {
            'a clear strategy': 0.564,
            'a strategy': 0.615,
            'a strong culture': 0.567,
            'an entrepreneurial spirit': 1.0,
            'an innovative culture': 0.981,
            'bold decisions': 1.0,
            'challenges': 0.572,
            'challenging experience': 0.571,
            'challenging opportunities': 0.568,
            'creativity': 0.606,
            'embrace change': 0.595,
            'embraces change': 1.0,
            'encourages experimentation': 1.0,
            'entrepreneurial spirit': 1.565,
            'experiences': 0.596,
            'experimentation': 0.582,
            'exploitation': 0.559,
            'exploration': 0.559,
            'fail fast': 1.0,
            'future success': 0.568,
            'hard decisions': 0.575,
            'innovation': 0.625,
            'innovative': 0.582,
            'innovative culture': 1.586,
            'innovative ways': 0.582,
            'innovative work': 0.554,
            'innovators': 0.567,
            'invaluable experience': 0.561,
            'learn': 0.567,
            'less innovation': 0.572,
            'lessons': 0.577,
            'limited experience': 0.563,
            'limited innovation': 0.569,
            'little innovation': 0.561,
            'more development': 0.601,
            'more innovation': 0.603,
            'more innovative': 0.56,
            'more learning': 0.556,
            'more marketing': 0.576,
            'more strategic': 0.573,
            'more successful': 0.557,
            'much development': 0.562,
            'much innovation': 0.62,
            'new experience': 0.598,
            'new experiences': 0.625,
            'new opportunities': 0.582,
            'new skills': 0.562,
            'new strategies': 0.619,
            'new strategy': 0.588,
            'our success': 0.562,
            'pushes boundaries': 1.0,
            'rapid change': 0.554,
            'strategies': 0.6,
            'strategy': 0.612,
            'strong commitment': 0.565,
            'strong culture': 0.555,
            'strong opportunities': 0.589,
            'strong purpose': 0.559,
            'success': 0.633,
            'takes risks': 1.0,
            'test': 1.322,
            'test and learn': 1.0,
            'the approach': 0.594,
            'the challenges': 0.573,
            'the entrepreneurial spirit': 1.0,
            'the experiences': 0.586,
            'the innovation': 0.614,
            'the innovative culture': 0.828,
            'the opportunities': 0.569,
            'the strategy': 0.599,
            'the success': 0.613,
            'tough decisions': 0.584,
            'true innovation': 0.565,
            'very entrepreneurial': 0.569,
            'willing to try new things': 1.0,
        },
        'negative': {
            'a concern': 0.529,
            'a hindrance': 0.532,
            'a risk': 0.629,
            'a safe environment': 0.567,
            'a threat': 0.511,
            'afraid of change': 1.0,
            'averse': 1.0,
            'avoid': 0.577,
            'caution': 0.582,
            'cautious to a fault': 1.0,
            'concern': 0.571,
            'concerns': 0.582,
            'conservative culture': 1.0,
            'constant fear': 0.642,
            'constant threat': 0.581,
            'constant threats': 0.593,
            'danger': 0.641,
            'dangerous work': 0.533,
            'extremely risk averse': 1.0,
            'fear': 1.669,
            'fear of failure': 1.0,
            'genuine concern': 0.512,
            'good safety': 0.509,
            'high risk': 0.572,
            'less risk': 1.0,
            'low risk': 0.601,
            'more concern': 0.519,
            'more concerned': 1.278,
            'more risk': 1.601,
            'more risks': 0.591,
            'more worried': 0.541,
            'our concerns': 0.51,
            'own risk': 0.597,
            'plays it safe': 1.0,
            'protection': 0.51,
            'psychological safety': 0.534,
            'resilience': 0.553,
            'resistant to new ideas': 1.0,
            'risk': 1.585,
            'risk averse': 1.0,
            'risk averse company': 0.88,
            'risk averse culture': 1.0,
            'risk management': 0.558,
            'risk taking': 0.676,
            'risk-averse': 1.0,
            'risk-averse culture': 0.903,
            'risks': 0.658,
            'safe environment': 0.556,
            'safety': 0.624,
            'safety culture': 0.519,
            'scare tactics': 0.551,
            'slow to innovate': 1.0,
            'status quo': 1.0,
            'status-quo': 1.0,
            'strong safety': 0.632,
            'survival': 0.6,
            'the concern': 0.557,
            'the concerns': 0.563,
            'the fear': 1.439,
            'the risk': 0.662,
            'the safety': 0.614,
            'the status quo': 1.0,
            'the status-quo': 1.0,
            'the threat': 0.53,
            'the uncertainty': 0.516,
            'threat': 0.533,
            'threats': 0.531,
            'too afraid': 0.534,
            'too risk averse': 1.0,
            'uncertain future': 0.508,
            'unsafe work': 0.541,
            'very conservative': 1.0,
            'very risk': 1.0,
            'very risk averse': 1.0,
            'warnings': 0.523,
            'your own risk': 0.594,
            'your safety': 0.542,
        },
    },
    'b08': {
        'positive': {
            'a meritocracy': 1.715,
            'a promotion': 0.645,
            'a real meritocracy': 0.903,
            'a rewarding experience': 0.628,
            'a true meritocracy': 0.938,
            'annual merit': 1.1,
            'best ideas win': 1.0,
            'competitive pay': 0.613,
            'competitive remuneration': 0.625,
            'competitive work': 0.642,
            'competitive working': 0.614,
            'earn your advancement': 1.0,
            'excellence': 0.718,
            'fair promotion process': 1.0,
            'fast promotion': 0.637,
            'fast promotions': 0.662,
            'incentive': 0.661,
            'incentive pay': 0.643,
            'incentives': 0.626,
            'internal promotions': 0.618,
            'less meritocracy': 0.944,
            'less promotion': 0.609,
            'less promotions': 0.625,
            'limited promotion opportunities': 0.616,
            'little meritocracy': 0.924,
            'low meritocracy': 0.828,
            'many promotions': 0.624,
            'merit': 0.739,
            'merit based': 1.0,
            'merit based growth': 0.88,
            'merit based promotion': 0.828,
            'merit based promotions': 0.842,
            'merit based raises': 0.799,
            'merit increases': 0.671,
            'merit-based promotions': 0.828,
            'merit-based raises': 0.828,
            'meritocracy': 1.682,
            'meritocracy culture': 0.855,
            'merits': 0.624,
            'more merit': 0.693,
            'more meritocracy': 0.868,
            'more promotions': 0.627,
            'most promotions': 0.609,
            'much meritocracy': 0.828,
            'performance based pay': 1.0,
            'poor meritocracy': 0.799,
            'promotion criteria': 0.654,
            'promotion opportunities': 0.688,
            'promotion opportunity': 0.669,
            'promotions': 0.621,
            'promotions based on performance': 1.0,
            'quick promotions': 0.608,
            'real meritocracy': 0.973,
            'recognition for good work': 1.0,
            'retaining talent': 0.609,
            'reward': 0.645,
            'rewarded for results': 1.0,
            'rewarding': 0.652,
            'rewarding career': 0.704,
            'rewarding company': 0.685,
            'rewarding employees': 0.678,
            'rewarding experience': 0.623,
            'rewarding job': 0.734,
            'rewarding work': 0.717,
            'rewards': 0.627,
            'talent gets recognised': 1.0,
            'talent management': 0.634,
            'the meritocracy': 0.792,
            'the promotion process': 0.646,
            'the promotions': 0.648,
            'timely promotions': 0.642,
            'true meritocracy': 1.0,
            'unfair promotions': 0.678,
            'yearly merit': 0.631,
        },
        'negative': {
            'a bit': 1.0,
            'a boys': 1.0,
            'a boys club': 1.0,
            'a role': 1.0,
            'an issue': 1.0,
            'an old boys': 1.0,
            'bad office': 1.0,
            'bad office politics': 1.0,
            'blatant favoritism': 1.53,
            'boys': 1.0,
            'brown-nosing': 1.0,
            'corruption': 1.522,
            'drama': 1.0,
            'extreme favoritism': 1.552,
            'favoritism': 1.581,
            'good old boys': 1.0,
            'good ole': 1.0,
            'good ole boys': 1.0,
            'heavy favoritism': 1.0,
            'heavy office': 1.0,
            'incompetence': 1.0,
            'less favoritism': 1.566,
            'less office': 1.0,
            'less office politics': 1.0,
            'management favoritism': 1.0,
            'micro': 1.0,
            'micromanagement': 0.667,
            'minimal office': 1.0,
            'much favoritism': 1.504,
            'much nepotism': 1.504,
            'nepotism': 1.05,
            'obvious favoritism': 1.554,
            'office politics': 1.634,
            'ol boys': 1.0,
            "ol' boys": 1.0,
            'old boys': 1.0,
            'old boys club': 0.667,
            'old school': 1.0,
            'ole boys': 1.0,
            'other employees': 1.0,
            'partiality': 1.0,
            'political culture': 1.596,
            'rampant favoritism': 1.552,
            'rampant nepotism': 1.551,
            'retaliation': 1.0,
            'so much favoritism': 1.0,
            'some favoritism': 1.575,
            'some nepotism': 1.0,
            'some office politics': 1.608,
            'strong office': 1.0,
            'supervisors': 1.0,
            'the boys': 1.0,
            'the boys club': 1.0,
            'the favoritism': 1.599,
            'the nepotism': 1.586,
            'the office politics': 1.602,
            'the store': 1.0,
            'too much favoritism': 1.505,
            'too much nepotism': 1.0,
            'typical office': 1.0,
            'typical office politics': 1.0,
            'usual office': 1.0,
            'very obvious': 1.0,
        },
    },
    'b09': {
        'positive': {
            'a healthy environment': 1.542,
            'a supportive culture': 1.0,
            'a supportive environment': 0.764,
            'a supportive team': 1.707,
            'compassionate leadership': 1.0,
            'diverse projects': 1.0,
            'excellent work-life balance': 1.507,
            'extremely supportive': 1.597,
            'flexible environment': 0.855,
            'flexible work environment': 1.0,
            'generally supportive': 1.62,
            'good collaboration': 0.944,
            'good healthy environment': 1.0,
            'good supportive culture': 0.981,
            'good supportive team': 1.0,
            'good work environment': 1.559,
            'good work-life balance': 1.489,
            'good working environment': 1.557,
            'great learning experience': 1.0,
            'great mentorship': 0.88,
            'great supportive culture': 1.0,
            'great supportive team': 1.0,
            'healthy environment': 1.0,
            'helpful management': 1.466,
            'helpful mentors': 0.999,
            'highly supportive': 1.546,
            'incredibly supportive': 1.552,
            'knowledgeable colleagues': 1.0,
            'low turnover': 1.0,
            'management cares': 1.0,
            'people stay for years': 1.0,
            'positive work environment': 1.0,
            'psychologically safe': 1.0,
            'real projects': 1.0,
            'really supportive': 1.0,
            'really supportive team': 1.0,
            'strong brand reputation': 0.855,
            'strong exposure': 0.88,
            'strong learning': 1.0,
            'strong learning opportunities': 1.0,
            'strong mentorship': 0.855,
            'strong support': 1.643,
            'strong support system': 1.0,
            'super supportive team': 0.999,
            'supportive company': 0.696,
            'supportive culture': 1.114,
            'supportive employees': 0.721,
            'supportive environment': 0.754,
            'supportive leaders': 0.7,
            'supportive leadership': 0.719,
            'supportive management': 0.748,
            'supportive manager': 0.7,
            'supportive managers': 0.72,
            'supportive team': 1.116,
            'supportive team atmosphere': 0.903,
            'supportive team culture': 1.662,
            'supportive team environment': 1.709,
            'supportive team leader': 0.924,
            'supportive team leaders': 1.0,
            'supportive team mates': 1.0,
            'supportive team member': 1.0,
            'supportive team members': 1.672,
            'supportive work environment': 0.686,
            'supportive workplace': 0.724,
            'the supportive culture': 1.0,
            'the supportive team': 0.88,
            'very healthy': 1.0,
            'very healthy environment': 1.0,
            'very supportive': 1.543,
            'very supportive culture': 1.0,
            'very supportive environment': 0.701,
            'very supportive management': 0.712,
            'very supportive team': 1.601,
            'work-life balance respected': 1.0,
        },
        'negative': {
            'a bullying culture': 1.0,
            'a high turnover': 1.536,
            'a toxic culture': 1.761,
            'a toxic environment': 1.727,
            'a toxic workplace': 1.0,
            'abuse': 1.549,
            'bad managers': 1.593,
            'bullying': 1.605,
            'bullying culture': 1.0,
            'burnout culture': 1.0,
            'constant bullying': 1.0,
            'corporate bullying': 1.0,
            'discrimination': 1.0,
            'extremely high turnover': 1.0,
            'extremely toxic': 1.625,
            'extremely toxic culture': 1.0,
            'extremely toxic environment': 1.0,
            'gossip': 1.0,
            'harassment': 1.561,
            'high turnover': 1.565,
            'high turnover rate': 1.512,
            'high turnover rates': 1.0,
            'highly toxic': 1.571,
            'hostile management': 1.0,
            'hostile work': 1.582,
            'incompetent management': 1.0,
            'incredibly toxic': 1.592,
            'intimidation': 1.0,
            'low morale': 1.598,
            "management doesn't care": 1.0,
            'most toxic': 1.609,
            'people leave constantly': 1.0,
            'poor communication': 1.0,
            'poor culture': 1.53,
            'racism': 1.0,
            'sexual harassment': 1.0,
            'such high turnover': 1.0,
            'tactics': 1.0,
            'terrible management': 1.583,
            'the bullying': 1.588,
            'the high turnover': 1.554,
            'the lack': 1.0,
            'the toxic culture': 1.725,
            'the toxic environment': 1.676,
            'this toxic culture': 1.0,
            'this toxic environment': 1.0,
            'toxic behavior': 0.737,
            'toxic behaviour': 0.737,
            'toxic colleagues': 0.729,
            'toxic company': 0.697,
            'toxic culture': 1.15,
            'toxic employees': 0.774,
            'toxic environment': 1.667,
            'toxic leadership': 0.71,
            'toxic management': 1.781,
            'toxic manager': 0.712,
            'toxic managers': 0.777,
            'toxic people': 0.706,
            'toxic work': 1.695,
            'toxic work culture': 0.73,
            'toxic work environment': 1.676,
            'toxic working': 0.744,
            'toxic working environment': 0.708,
            'toxic workplace': 1.795,
            'toxic workplace culture': 1.0,
            'very high turnover': 1.0,
            'very toxic': 1.596,
            'very toxic culture': 1.0,
            'very toxic environment': 1.644,
            'workplace bullying': 1.584,
        },
    },
    'b10': {
        'positive': {
            'a consistent strategy': 1.0,
            'a reliable employer': 0.924,
            'a stable company': 1.721,
            'big stable company': 1.0,
            'big, stable company': 0.855,
            'clear direction': 1.0,
            'consistent leadership': 0.753,
            'consistent priorities': 1.0,
            'consistent strategy': 1.0,
            'decent benefits': 0.888,
            'decent compensation': 0.828,
            'extremely stable': 1.0,
            'extremely stable company': 0.855,
            'fairly stable': 1.565,
            'fairly stable company': 1.0,
            'financially stable': 1.61,
            'financially stable company': 1.0,
            'good company culture': 0.799,
            'good coworkers': 0.855,
            'good employee': 1.0,
            'good health': 0.944,
            'good job security': 0.855,
            'good reputation': 0.88,
            'good salaries': 0.963,
            'good stable company': 1.683,
            'good support': 0.799,
            'good training': 0.914,
            'good work/life balance': 0.924,
            'good, stable company': 1.0,
            'great leadership': 1.0,
            'great stable company': 1.0,
            'great work/life balance': 0.828,
            'great, stable company': 1.0,
            'large stable company': 1.0,
            'large, stable company': 1.0,
            'most stable': 0.944,
            'nice offices': 0.799,
            'nice stable company': 0.828,
            'overall stable company': 0.88,
            'predictable and dependable': 1.0,
            'pretty stable': 1.554,
            'pretty stable company': 0.963,
            'relatively stable': 1.597,
            'relatively stable company': 1.0,
            'reliable employer': 1.552,
            'solid stable company': 1.0,
            'solid, stable company': 1.0,
            'stable company': 1.132,
            'stable industry': 1.464,
            'stable job': 1.709,
            'stable management': 1.777,
            'steady growth': 0.944,
            'steady leadership': 1.0,
            'sticks to the plan': 1.0,
            'strong brand': 0.768,
            'strong leadership': 1.5,
            'strong market': 1.351,
            'strong stable company': 1.0,
            'strong, stable company': 1.0,
            'very stable': 1.546,
            'very stable company': 1.673,
            'well organised': 1.0,
            'well organised company': 1.0,
            'well organised structure': 0.855,
            'wide range': 0.799,
        },
        'negative': {
            'a chaotic environment': 1.0,
            'a chaotic mess': 0.924,
            'a little disorganised': 0.924,
            'a reorganization': 0.66,
            'absolutely chaotic': 0.855,
            'always chaotic': 0.981,
            'chaotic': 1.0,
            'chaotic atmosphere': 1.0,
            'chaotic change': 0.855,
            'chaotic changes': 0.999,
            'chaotic culture': 1.0,
            'chaotic decision': 1.0,
            'chaotic environment': 1.0,
            'chaotic experience': 0.944,
            'chaotic hr': 0.799,
            'chaotic mess': 1.0,
            'chaotic organisation': 1.0,
            'chaotic organization': 1.0,
            'chaotic place': 1.0,
            'chaotic process': 0.855,
            'chaotic processes': 1.0,
            'chaotic situation': 0.799,
            'chaotic structure': 1.0,
            'chaotic way': 0.963,
            'chaotic work': 1.533,
            'chaotic working': 1.0,
            'chaotic, lack': 0.828,
            'completely chaotic': 0.903,
            'constant reorganisation': 1.0,
            'constant restructuring': 1.643,
            'disorganised': 1.0,
            'disorganised chaos': 0.924,
            'disorganised company': 1.0,
            'disorganised environment': 0.799,
            'disorganised management': 1.0,
            'disorganised structure': 0.855,
            'extremely chaotic': 1.0,
            'extremely disorganised': 1.0,
            'favouritism': 0.88,
            'flavor': 1.0,
            'flavor of the month': 1.0,
            'highly chaotic': 0.855,
            'leadership changes': 1.416,
            'leadership churn': 1.0,
            'left hand': 0.903,
            "left hand doesn't know what the right is doing": 1.0,
            'less chaotic': 1.0,
            'little disorganised': 0.944,
            'more chaotic': 1.0,
            'most chaotic': 0.999,
            'of chaotic': 0.855,
            'often chaotic': 1.0,
            'pretty chaotic': 1.0,
            'quite chaotic': 1.0,
            'quite disorganised': 1.0,
            'rather chaotic': 0.903,
            'really chaotic': 1.0,
            'shifting priorities': 1.0,
            'shifts': 1.396,
            'slightly chaotic': 1.0,
            'so chaotic': 1.0,
            'sometimes chaotic': 1.0,
            'somewhat chaotic': 1.0,
            'somewhat disorganised': 0.924,
            'strategy changes every year': 1.0,
            'super chaotic': 0.855,
            'the chaotic environment': 0.828,
            'the constant restructuring': 1.0,
            'the flavor': 1.0,
            'the month': 1.0,
            'the right': 0.88,
            'too chaotic': 1.0,
            'very chaotic': 1.556,
            'very chaotic environment': 0.855,
            'very disorganised': 1.567,
        },
    },
    'b11': {
        'positive': {
            'accountability': 0.688,
            'an ethical company': 1.0,
            'authenticity': 0.581,
            'best ethical company': 0.855,
            'commitment': 0.944,
            'competent leadership': 0.578,
            'competitive compensation': 0.672,
            'credibility': 0.575,
            'distrust': 0.605,
            'does the right thing': 1.0,
            'ethical company': 1.602,
            'ethical standards': 1.679,
            'ethical values': 0.636,
            'extremely ethical company': 0.88,
            'global company': 0.855,
            'good brand': 0.828,
            'good compensation': 0.903,
            'good ethical company': 1.0,
            'good ethics': 0.655,
            'good leadership': 0.586,
            'good products': 0.828,
            'good work ethics': 0.606,
            'great company culture': 0.88,
            'great ethical company': 1.0,
            'great ethics': 0.584,
            'great work ethics': 0.594,
            'high ethical standards': 1.0,
            'high integrity': 1.745,
            'high integrity company': 0.944,
            'highly ethical': 1.664,
            'highly ethical company': 1.0,
            'holds itself accountable': 1.0,
            'honest communication': 0.576,
            'honest leadership': 1.0,
            'integrity': 0.791,
            'integrity matters here': 1.0,
            'little accountability': 0.599,
            'low accountability': 0.591,
            'more accountability': 0.604,
            'more trustworthy': 0.903,
            'most ethical': 1.625,
            'most ethical company': 1.0,
            'positive culture': 0.903,
            'principles': 0.963,
            'responsibility': 0.597,
            'right thing': 0.77,
            'solid company': 0.88,
            'strong ethical standards': 0.828,
            'strong ethics': 0.721,
            'strong values': 1.546,
            'sustainability': 0.88,
            'the integrity': 0.779,
            'the right thing': 0.791,
            'the trust': 0.598,
            'transparent management': 1.0,
            'trust': 0.634,
            'trust employees': 0.578,
            'trustworthy': 1.0,
            'trustworthy company': 1.0,
            'trustworthy employees': 0.981,
            'trustworthy employer': 0.828,
            'trustworthy environment': 0.855,
            'trustworthy leaders': 0.828,
            'trustworthy leadership': 1.0,
            'trustworthy management': 1.0,
            'trustworthy people': 1.0,
            'very ethical company': 1.0,
            'very high integrity': 0.799,
            'very strong': 1.0,
            'very strong values': 1.0,
            'very transparent management': 0.828,
            'very trustworthy': 1.0,
        },
        'negative': {
            'a blind eye': 0.649,
            'abusive customers': 0.546,
            'bad behaviour': 0.555,
            'bad business': 0.54,
            'bad customers': 0.548,
            'bad practices': 0.642,
            'blind eye': 0.732,
            'corners': 1.0,
            'corporate rules': 0.567,
            'cover up': 1.0,
            'cutting corners': 1.0,
            'cutting edge': 0.543,
            'dishonest management': 1.618,
            'extremely shady': 1.0,
            'fraud': 0.557,
            'high pressure': 0.624,
            'issues': 1.084,
            'little shady': 0.903,
            'look the other way': 1.0,
            'misleading customers': 1.0,
            'mismanagement': 0.547,
            'mistakes': 1.034,
            'overly bureaucratic': 0.548,
            'pressure to bend the rules': 1.0,
            'pretty shady': 0.981,
            'problems': 0.789,
            'questionable decisions': 0.591,
            'questionable ethics': 1.712,
            'questionable management': 0.585,
            'really shady': 0.963,
            'regulatory issues': 1.0,
            'shady': 1.0,
            'shady behavior': 0.828,
            'shady business': 1.0,
            'shady business practices': 1.0,
            'shady company': 1.0,
            'shady coworkers': 0.799,
            'shady dealings': 0.944,
            'shady deals': 0.903,
            'shady employees': 0.799,
            'shady management': 1.0,
            'shady people': 1.0,
            'shady place': 0.88,
            'shady practice': 0.855,
            'shady practices': 1.755,
            'shady sales': 1.0,
            'shady sales practices': 0.999,
            'shady sales tactics': 1.0,
            'shady stuff': 1.0,
            'shady tactics': 1.0,
            'shady things': 1.0,
            'shady way': 0.924,
            'shady work': 0.828,
            'so shady': 1.0,
            'strict regulations': 0.541,
            'super shady': 0.924,
            'the other way': 1.0,
            'the unethical practices': 0.799,
            'the way': 0.799,
            'tough customers': 0.552,
            'unethical behavior': 0.677,
            'unethical business': 0.677,
            'unethical company': 0.612,
            'unethical management': 0.67,
            'unethical practices': 1.695,
            'unethical sales': 0.617,
            'unethical things': 0.668,
            'unfair management': 0.561,
            'unfair practices': 0.686,
            'unfairness': 0.546,
            'unruly customers': 0.585,
            'very shady': 1.0,
            'very unethical': 0.594,
            'wrong decisions': 0.555,
        },
    },
    'b12': {
        'positive': {
            'a diverse group': 0.742,
            'a diverse workforce': 1.725,
            'an inclusive culture': 1.769,
            'an inclusive environment': 1.754,
            'belonging': 1.0,
            'celebrates differences': 1.0,
            'collaborative environment': 0.667,
            'cultural diversity': 0.76,
            'culturally diverse': 0.732,
            'diverse': 1.707,
            'diverse background': 0.669,
            'diverse backgrounds': 0.744,
            'diverse business': 0.687,
            'diverse career': 0.709,
            'diverse community': 0.732,
            'diverse culture': 0.751,
            'diverse cultures': 0.702,
            'diverse employee': 0.694,
            'diverse employees': 0.733,
            'diverse environment': 0.703,
            'diverse experience': 0.74,
            'diverse experiences': 0.717,
            'diverse group': 0.734,
            'diverse leadership team': 1.0,
            'diverse opportunities': 0.781,
            'diverse people': 0.725,
            'diverse perspectives': 0.674,
            'diverse roles': 0.695,
            'diverse staff': 0.711,
            'diverse team': 0.681,
            'diverse teams': 0.69,
            'diverse work': 0.733,
            'diverse work environment': 0.708,
            'diverse workforce': 1.723,
            'diverse working': 0.768,
            'diverse workplace': 0.771,
            'diversity and inclusion': 1.0,
            'equal opportunities': 1.602,
            'ethnic diversity': 0.683,
            'global presence': 1.0,
            'good diversity': 1.63,
            'good inclusive culture': 1.0,
            'great diversity': 1.599,
            'great inclusive culture': 1.0,
            'inclusion': 1.499,
            'inclusion culture': 1.0,
            'inclusion efforts': 1.0,
            'inclusion initiatives': 1.0,
            'inclusion program': 1.0,
            'inclusion programs': 1.0,
            'inclusion training': 1.0,
            'inclusive company': 0.673,
            'inclusive culture': 1.175,
            'inclusive environment': 1.728,
            'inclusive work': 0.669,
            'inclusive work environment': 0.666,
            'inclusive workplace': 1.743,
            'inclusiveness': 0.719,
            'less diversity': 0.682,
            'limited diversity': 0.7,
            'little diversity': 0.681,
            'more diverse': 0.684,
            'more diversity': 1.709,
            'most diverse': 0.656,
            'multicultural': 0.676,
            'multicultural environment': 0.662,
            'racial diversity': 0.707,
            'strong diversity': 1.693,
            'supportive culture': 1.07,
            'the diversity': 1.764,
            'the inclusive culture': 1.0,
            'their diversity': 1.0,
            'true diversity': 0.667,
            'very diverse': 1.641,
            'very diverse workforce': 1.0,
            'very inclusive': 1.583,
            'very inclusive culture': 1.0,
            'very inclusive environment': 1.0,
            'welcoming to everyone': 1.0,
            'women in leadership': 1.0,
        },
        'negative': {
            'a clique': 0.558,
            'a clique culture': 0.828,
            'a glass ceiling': 1.0,
            'a huge lack': 0.903,
            'a lack': 0.73,
            'a workforce': 0.526,
            'all male leadership': 1.0,
            'clique culture': 1.0,
            'cliques': 0.538,
            'cliquey': 0.551,
            'club': 1.424,
            'club mentality': 0.784,
            'clubs': 0.514,
            'diversity is lip service': 1.0,
            'extreme lack': 0.693,
            'female employees': 0.532,
            'female leaders': 0.556,
            'female leadership': 0.573,
            'female managers': 0.561,
            'female staff': 0.511,
            'few leaders': 0.527,
            'few managers': 0.511,
            'gender': 0.538,
            'glass ceiling': 1.0,
            'groupism': 0.53,
            'homogeneous workforce': 1.0,
            'huge lack': 0.868,
            'lack': 1.0,
            'leaders': 0.55,
            'less managers': 0.509,
            'low glass': 0.855,
            'males': 0.522,
            'modern workplace': 0.519,
            'more leaders': 0.515,
            'new leadership': 0.52,
            'old boys club': 0.667,
            'our leadership': 0.53,
            'poor leadership': 1.229,
            'senior leadership': 0.734,
            'senior managers': 0.592,
            'serious lack': 0.597,
            'severe lack': 0.578,
            'sexism': 0.556,
            'society': 0.521,
            'some management': 0.517,
            'some senior management': 0.51,
            'sr. leadership': 0.51,
            'the clique': 0.6,
            'the glass ceiling': 1.0,
            'the leaders': 0.515,
            'the leadership': 0.545,
            'the leadership level': 0.54,
            'the management style': 0.52,
            'the new leadership': 0.531,
            'the old boys': 1.0,
            'the senior leaders': 0.517,
            'the senior leadership': 0.52,
            'the senior managers': 0.513,
            'the society': 0.53,
            'the workforce': 0.541,
            'the younger generation': 0.514,
            'their leadership': 0.533,
            'tokenism': 1.0,
            'very clique': 0.521,
            'white males': 0.549,
            'workforce': 0.552,
            'young generation': 0.519,
            'young leaders': 0.548,
            'young managers': 0.528,
            'youth': 0.528,
        },
    },
}


SCHRODERS_V2_DIM_INFO = {
    "b01": {
        "title": "Short-term ↔ Long-term",
        "left_label": "Short-term / quarterly",
        "right_label": "Long-term / patient",
        "description": "Whether the company chases short-term results (lower score) or plans patiently for the long term (higher score).",
        "thesis": "Long-term orientation predicts capex quality and R&D productivity."
    },
    "b02": {
        "title": "Cost-focused ↔ Growth-focused",
        "left_label": "Cost-focused / thrifty",
        "right_label": "Growth-focused / investing",
        "description": "Whether the company prioritises cutting costs (lower score) or investing in growth (higher score). Both can be legitimate.",
        "thesis": "Alignment with value vs growth strategy."
    },
    "b03": {
        "title": "Hierarchical ↔ Egalitarian",
        "left_label": "Hierarchical / top-down",
        "right_label": "Egalitarian / distributed",
        "description": "Whether decisions flow top-down through layers (lower score) or power is shared more equally (higher score).",
        "thesis": "Egalitarian predicts faster decisions and retention in knowledge industries."
    },
    "b04": {
        "title": "Rules-driven ↔ Judgement-driven",
        "left_label": "Rules-driven / process",
        "right_label": "Judgement-driven / adaptive",
        "description": "Whether work is governed by defined processes and rules (lower score) or by individual judgement and adaptability (higher score).",
        "thesis": "Rules-driven suits regulated industries; judgement-driven suits volatile ones."
    },
    "b05": {
        "title": "Individual ↔ Team performance",
        "left_label": "Individual performance",
        "right_label": "Team performance",
        "description": "Whether performance is about individual achievement (lower score) or collective teamwork (higher score).",
        "thesis": "Individual outperformance for sales; team outperformance for engineering."
    },
    "b06": {
        "title": "Insular ↔ Externally-focused",
        "left_label": "Insular / internally-driven",
        "right_label": "Externally-focused / market-driven",
        "description": "Whether the company looks inward at itself (lower score) or outward at customers and markets (higher score).",
        "thesis": "Externally-focused predicts better response to disruption."
    },
    "b07": {
        "title": "Risk-averse ↔ Risk-taking",
        "left_label": "Risk-averse",
        "right_label": "Risk-taking",
        "description": "Whether the company avoids risk (lower score) or embraces experimentation and bold moves (higher score).",
        "thesis": "Risk-taking gives growth optionality; risk-aversion gives drawdown protection."
    },
    "b08": {
        "title": "Political ↔ Meritocratic",
        "left_label": "Political / tenure-based",
        "right_label": "Meritocratic / performance-based",
        "description": "Whether advancement depends on politics and tenure (lower score) or on merit and performance (higher score).",
        "thesis": "Meritocracy predicts talent retention and productivity."
    },
    "b09": {
        "title": "Toxic ↔ Supportive",
        "left_label": "Toxic / high-turnover",
        "right_label": "Supportive / low-turnover",
        "description": "Whether the environment is hostile and burns people out (lower score) or supports and retains them (higher score).",
        "thesis": "Retention cost and hiring quality."
    },
    "b10": {
        "title": "Chaotic ↔ Stable",
        "left_label": "Chaotic / strategy churn",
        "right_label": "Stable / consistent",
        "description": "Whether direction changes constantly (lower score) or strategy and organisation are consistent (higher score).",
        "thesis": "Execution quality."
    },
    "b11": {
        "title": "Compliance-minimising ↔ Integrity-maximising",
        "left_label": "Compliance-minimising",
        "right_label": "Integrity-maximising",
        "description": "Whether the company cuts ethical corners (lower score) or holds itself to high standards of integrity (higher score).",
        "thesis": "Reduced regulatory and reputational tail risk."
    },
    "b12": {
        "title": "Homogeneous ↔ Diverse & inclusive",
        "left_label": "Homogeneous",
        "right_label": "Diverse & inclusive",
        "description": "Whether the workforce and leadership are uniform (lower score) or genuinely diverse and inclusive (higher score).",
        "thesis": "DEI correlates with decision quality where evidence supports it."
    }
}
